apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: news-service-dev
  namespace: argocd
  labels:
    env: dev
    service: news-service
  annotations:
    github.com/deployment-id: "5179323367"
    github.com/repo: tf-systems/tf-news-service
    github.com/log-url: https://github.com/tf-systems/tf-news-service/actions/runs/28091087521
    github.com/environment-url: https://github.com/tf-systems/tf-news-service-deployment/pulls?q=is%3Apr+head%3Adeploy%2Fnews-service%2Fdev%2Fv0.3.0
spec:
  project: default
  sources:
    - repoURL: ghcr.io/tf-systems/charts
      chart: news-service
      targetRevision: 0.3.0
      helm:
        releaseName: news-service
        valueFiles:
          - $values/environments/dev/values.yaml
    - repoURL: https://github.com/tf-systems/tf-news-service-deployment
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: news-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
