apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: news-service-dev
  namespace: argocd
  labels:
    env: dev
    service: news-service
spec:
  project: default
  sources:
    - repoURL: ghcr.io/tf-systems/charts
      chart: news-service
      targetRevision: 0.0.1-feat-ghcr-smoke-etappe3.82dcf21
      helm:
        releaseName: news-service
        valueFiles:
          - $values/environments/dev/values.yaml
    - repoURL: https://github.com/tf-systems/tf-news-service-deployment
      targetRevision: feat/ghcr-smoke-etappe3
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: news-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
